import { PrismaClient, FenceCategory } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('Seeding FencePro database...');

  const configEntries = [
    { key: 'man_hour_rate',           value: '22.00' },
    { key: 'commission_salesman',     value: '0.10' },
    { key: 'commission_non_salesman', value: '0.00' },
    { key: 'overhead_rate',           value: '0.30' },
    { key: 'tear_out_fence_cost',     value: '9.50' },
    { key: 'tear_out_gate_cost',      value: '27.00' },
    { key: 'monthly_revenue_goal',    value: '80000.00' },
    { key: 'price_adjust_cap',        value: '0.20' },
    { key: 'goal_gm_pct',             value: '0.62' },
  ];

  for (const entry of configEntries) {
    await prisma.systemConfig.upsert({
      where:  { key: entry.key },
      update: { value: entry.value },
      create: entry,
    });
  }
  console.log(`  ✓ ${configEntries.length} config entries`);

  const fenceStyles: Array<{
  name: string;
  category: FenceCategory;
  margin: number;
  sectionsPerMH: number;
  mhPerWalkGate: number;
  mhPerDblGate: number;
  isNoDig: boolean;
}> = [
    { name: "WV-ND 6'x6' Privacy",    category: 'VINYL',      margin: 0.64, sectionsPerMH: 1.2,  mhPerWalkGate: 2.4, mhPerDblGate: 4.8, isNoDig: true  },
    { name: "WV-ND 6'x8' Privacy",    category: 'VINYL',      margin: 0.64, sectionsPerMH: 1.2,  mhPerWalkGate: 2.4, mhPerDblGate: 4.8, isNoDig: true  },
    { name: "WV-ND 8'x6' Privacy",    category: 'VINYL',      margin: 0.64, sectionsPerMH: 0.8,  mhPerWalkGate: 1.6, mhPerDblGate: 3.2, isNoDig: true  },
    { name: "WV-ND 8'x8' Privacy",    category: 'VINYL',      margin: 0.64, sectionsPerMH: 0.8,  mhPerWalkGate: 1.6, mhPerDblGate: 3.2, isNoDig: true  },
    { name: "WV-ND Bell 4'x6'",       category: 'VINYL',      margin: 0.64, sectionsPerMH: 1.25, mhPerWalkGate: 2.5, mhPerDblGate: 5.0, isNoDig: true  },
    { name: "WV-DS 6'x6' Privacy",    category: 'VINYL',      margin: 0.64, sectionsPerMH: 0.8,  mhPerWalkGate: 1.6, mhPerDblGate: 3.2, isNoDig: false },
    { name: "WV-DS 6'x8' Privacy",    category: 'VINYL',      margin: 0.64, sectionsPerMH: 0.8,  mhPerWalkGate: 1.6, mhPerDblGate: 3.2, isNoDig: false },
    { name: "WV-DS 8'x6' Privacy",    category: 'VINYL',      margin: 0.64, sectionsPerMH: 0.7,  mhPerWalkGate: 1.4, mhPerDblGate: 2.8, isNoDig: false },
    { name: "WV-DS 8'x8' Privacy",    category: 'VINYL',      margin: 0.64, sectionsPerMH: 0.7,  mhPerWalkGate: 1.4, mhPerDblGate: 2.8, isNoDig: false },
    { name: "TV-ND 6'x6' Privacy",    category: 'VINYL',      margin: 0.64, sectionsPerMH: 1.2,  mhPerWalkGate: 2.4, mhPerDblGate: 4.8, isNoDig: true  },
    { name: "TV-ND 6'x8' Privacy",    category: 'VINYL',      margin: 0.64, sectionsPerMH: 1.5,  mhPerWalkGate: 3.0, mhPerDblGate: 6.0, isNoDig: true  },
    { name: "TV-ND 8'x6' Privacy",    category: 'VINYL',      margin: 0.64, sectionsPerMH: 1.0,  mhPerWalkGate: 2.0, mhPerDblGate: 4.0, isNoDig: true  },
    { name: "TV-ND 8'x8' Privacy",    category: 'VINYL',      margin: 0.64, sectionsPerMH: 1.0,  mhPerWalkGate: 2.0, mhPerDblGate: 4.0, isNoDig: true  },
    { name: "TV-DS 6'x6' Privacy",    category: 'VINYL',      margin: 0.64, sectionsPerMH: 1.1,  mhPerWalkGate: 2.2, mhPerDblGate: 4.4, isNoDig: false },
    { name: "TV-DS 6'x8' Privacy",    category: 'VINYL',      margin: 0.64, sectionsPerMH: 1.1,  mhPerWalkGate: 2.2, mhPerDblGate: 4.4, isNoDig: false },
    { name: "TV-DS 8'x6' Privacy",    category: 'VINYL',      margin: 0.64, sectionsPerMH: 0.8,  mhPerWalkGate: 1.6, mhPerDblGate: 3.2, isNoDig: false },
    { name: "TV-DS 8'x8' Privacy",    category: 'VINYL',      margin: 0.64, sectionsPerMH: 0.8,  mhPerWalkGate: 1.6, mhPerDblGate: 3.2, isNoDig: false },
    { name: "CL - 4' Galv",           category: 'CHAINLINK',  margin: 0.56, sectionsPerMH: 1.5,  mhPerWalkGate: 3.0, mhPerDblGate: 6.0, isNoDig: false },
    { name: "CL - 5' Galv",           category: 'CHAINLINK',  margin: 0.56, sectionsPerMH: 1.5,  mhPerWalkGate: 3.0, mhPerDblGate: 6.0, isNoDig: false },
    { name: "CL - 6' Galv",           category: 'CHAINLINK',  margin: 0.56, sectionsPerMH: 1.5,  mhPerWalkGate: 3.0, mhPerDblGate: 6.0, isNoDig: false },
    { name: "CL - 4' Black",          category: 'CHAINLINK',  margin: 0.56, sectionsPerMH: 1.5,  mhPerWalkGate: 3.0, mhPerDblGate: 6.0, isNoDig: false },
    { name: "CL - 5' Black",          category: 'CHAINLINK',  margin: 0.56, sectionsPerMH: 1.5,  mhPerWalkGate: 3.0, mhPerDblGate: 6.0, isNoDig: false },
    { name: "CL - 6' Black",          category: 'CHAINLINK',  margin: 0.56, sectionsPerMH: 1.5,  mhPerWalkGate: 3.0, mhPerDblGate: 6.0, isNoDig: false },
    { name: "CL - Com 6'",            category: 'COMMERCIAL', margin: 0.56, sectionsPerMH: 1.0,  mhPerWalkGate: 2.0, mhPerDblGate: 4.0, isNoDig: false },
    { name: "CL - Com 6' Black",      category: 'COMMERCIAL', margin: 0.56, sectionsPerMH: 1.0,  mhPerWalkGate: 2.0, mhPerDblGate: 4.0, isNoDig: false },
    { name: "CL - Com 6' Green",      category: 'COMMERCIAL', margin: 0.56, sectionsPerMH: 1.0,  mhPerWalkGate: 2.0, mhPerDblGate: 4.0, isNoDig: false },
    { name: "CL - Com 6'+1'",         category: 'COMMERCIAL', margin: 0.56, sectionsPerMH: 1.0,  mhPerWalkGate: 2.0, mhPerDblGate: 4.0, isNoDig: false },
    { name: "CL - Com 6'+1' Black",   category: 'COMMERCIAL', margin: 0.56, sectionsPerMH: 1.0,  mhPerWalkGate: 2.0, mhPerDblGate: 4.0, isNoDig: false },
    { name: "CL - Com 6'+1' Green",   category: 'COMMERCIAL', margin: 0.56, sectionsPerMH: 1.0,  mhPerWalkGate: 2.0, mhPerDblGate: 4.0, isNoDig: false },
    { name: "Alum - DS - Emily - 48", category: 'ALUMINUM',   margin: 0.62, sectionsPerMH: 1.2,  mhPerWalkGate: 2.4, mhPerDblGate: 4.8, isNoDig: false },
    { name: "Alum - ND - Emily - 48", category: 'ALUMINUM',   margin: 0.64, sectionsPerMH: 1.5,  mhPerWalkGate: 3.0, mhPerDblGate: 6.0, isNoDig: true  },
    { name: "Alum - DS - Abigaill",   category: 'ALUMINUM',   margin: 0.60, sectionsPerMH: 1.2,  mhPerWalkGate: 2.4, mhPerDblGate: 4.8, isNoDig: false },
    { name: "Alum - DS - Ind Abigail",category: 'ALUMINUM',   margin: 0.58, sectionsPerMH: 1.2,  mhPerWalkGate: 2.4, mhPerDblGate: 4.8, isNoDig: false },
    { name: "Misc 6' Sec",            category: 'OTHER',      margin: 0.64, sectionsPerMH: 1.25, mhPerWalkGate: 2.5, mhPerDblGate: 5.0, isNoDig: false },
    { name: "Durafence",              category: 'OTHER',      margin: 0.64, sectionsPerMH: 1.0,  mhPerWalkGate: 2.0, mhPerDblGate: 4.0, isNoDig: false },
  ];

  for (const style of fenceStyles) {
    await prisma.fenceStyle.upsert({
      where:  { name: style.name },
      update: style,
      create: style,
    });
  }
  console.log(`  ✓ ${fenceStyles.length} fence styles`);

  const inventoryItems = [
    { name: 'Tear Out Haul-Away Gate',               cost: 27.00,  category: 'tearout'  },
    { name: 'Tear Out Haul-Away Fence',              cost: 9.50,   category: 'tearout'  },
    { name: "Alum, 3-Rail, Emily, Gate, 4' x 4', 48\"", cost: 168.83, category: 'gate' },
    { name: "Alum, 3-Rail, Emily, Gate, 4' x 5', 48\"", cost: 183.69, category: 'gate' },
    { name: "Alum, 3-Rail, Emily, Gate, 4' x 6', 48\"", cost: 196.38, category: 'gate' },
    { name: "Alum, Emily 3R, Sec, 48\" x 6'",       cost: 54.88,  category: 'section'  },
    { name: "Emily 3R 48\", CP x 6'",               cost: 14.78,  category: 'post'     },
    { name: "Emily 3R 48\", EP x 6'",               cost: 14.78,  category: 'post'     },
    { name: "Emily 3R 48\", LP x 6'",               cost: 14.78,  category: 'post'     },
    { name: "Chainlink, Black, Gate, 4' x 4'",      cost: 123.95, category: 'gate'     },
    { name: "Chainlink, Black, Gate, 4' x 5'",      cost: 133.69, category: 'gate'     },
    { name: "Chainlink, Black, Gate, 4' x 6'",      cost: 143.42, category: 'gate'     },
    { name: "Chainlink, Black, Gate, 5' x 4'",      cost: 138.46, category: 'gate'     },
    { name: "Chainlink, Black, Gate, 5' x 5'",      cost: 173.51, category: 'gate'     },
    { name: "Chainlink, Black, Gate, 5' x 6'",      cost: 194.50, category: 'gate'     },
    { name: "Chainlink, Black, Gate, 6' x 4'",      cost: 154.66, category: 'gate'     },
    { name: "Chainlink, Black, Gate, 6' x 5'",      cost: 175.27, category: 'gate'     },
    { name: "Chainlink, Black, Gate, 6' x 6'",      cost: 197.35, category: 'gate'     },
    { name: "Chainlink, Galv, Gate, 4' x 4'",       cost: 85.00,  category: 'gate'     },
    { name: "Chainlink, Galv, Gate, 4' x 5'",       cost: 90.28,  category: 'gate'     },
    { name: "Chainlink, Galv, Gate, 4' x 6'",       cost: 99.51,  category: 'gate'     },
    { name: "Chainlink, Galv, Gate, 5' x 4'",       cost: 88.85,  category: 'gate'     },
    { name: "Chainlink, Galv, Gate, 5' x 5'",       cost: 102.45, category: 'gate'     },
    { name: "Chainlink, Galv, Gate, 5' x 6'",       cost: 115.67, category: 'gate'     },
    { name: "Chainlink, Galv, Gate, 6' x 4'",       cost: 114.86, category: 'gate'     },
    { name: "Chainlink, Galv, Gate, 6' x 5'",       cost: 130.08, category: 'gate'     },
    { name: "Chainlink, Galv, Gate, 6' x 6'",       cost: 146.41, category: 'gate'     },
    { name: 'Misc, Concrete',                        cost: 6.25,   category: 'misc'     },
    { name: 'ND, Donut',                             cost: 3.19,   category: 'hardware' },
    { name: "Res, Fabric, 48\", Blk",               cost: 116.16, category: 'fabric'   },
    { name: "Res, Fabric, 60\", Blk",               cost: 145.20, category: 'fabric'   },
    { name: "Res, Fabric, 72\", Blk",               cost: 174.24, category: 'fabric'   },
    { name: "Pipe, Blk, 1-5/8\" X 8'",             cost: 21.50,  category: 'pipe'     },
    { name: "Pipe, Blk, 1-5/8\" X 9'",             cost: 24.19,  category: 'pipe'     },
    { name: "Pipe, Blk, 1-5/8\" X 10'",            cost: 26.87,  category: 'pipe'     },
    { name: "Black, Tension Bar, 48\"",             cost: 4.25,   category: 'hardware' },
    { name: "Black, Tension Bar, 60\"",             cost: 5.45,   category: 'hardware' },
    { name: "Black, Tension Bar, 72\"",             cost: 4.62,   category: 'hardware' },
    { name: "Pipe, Blk, 2-1/2\" X 8'",             cost: 44.07,  category: 'pipe'     },
    { name: "Pipe, Blk, 2-1/2\" X 9'",             cost: 49.58,  category: 'pipe'     },
    { name: "Pipe, Blk, 2-1/2\" X 10'",            cost: 55.08,  category: 'pipe'     },
    { name: "Fabric, Galv, 48\"",                   cost: 113.43, category: 'fabric'   },
    { name: "Fabric, Galv, 60\"",                   cost: 137.50, category: 'fabric'   },
    { name: "Fabric, Galv, 72\"",                   cost: 166.37, category: 'fabric'   },
    { name: "Pipe, Galv, 1-5/8\" X 8'",            cost: 16.49,  category: 'pipe'     },
    { name: "Pipe, Galv, 1-5/8\" X 9'",            cost: 18.55,  category: 'pipe'     },
    { name: "Pipe, Galv, 1-5/8\" X 10'",           cost: 20.61,  category: 'pipe'     },
    { name: "G, Tension Bar, 48\"",                 cost: 3.01,   category: 'hardware' },
    { name: "G, Tension Bar, 60\"",                 cost: 3.75,   category: 'hardware' },
    { name: "G, Tension Bar, 72\"",                 cost: 4.00,   category: 'hardware' },
    { name: "Pipe, Galv, 2-1/2\" X 8'",            cost: 28.13,  category: 'pipe'     },
    { name: "Pipe, Galv, 2-1/2\" X 9'",            cost: 34.76,  category: 'pipe'     },
    { name: "Pipe, Galv, 2-1/2\" X 10'",           cost: 34.99,  category: 'pipe'     },
    { name: "*Vinyl, White, Post, Corner, 78\"",    cost: 11.17,  category: 'vinyl'    },
    { name: "*Vinyl, White, Post, End, 78\"",       cost: 11.17,  category: 'vinyl'    },
    { name: "*Vinyl, White, Post, Line, 78\"",      cost: 11.17,  category: 'vinyl'    },
    { name: "*Vinyl, White, Post, Corner, 102\"",   cost: 13.64,  category: 'vinyl'    },
    { name: "*Vinyl, White, Post, End, 102\"",      cost: 13.64,  category: 'vinyl'    },
    { name: "*Vinyl, White, Post, Line, 102\"",     cost: 17.49,  category: 'vinyl'    },
    { name: "*Vinyl, White, Picket",                cost: 2.71,   category: 'vinyl'    },
    { name: "*Vinyl, White, Rail, 6'",              cost: 5.98,   category: 'vinyl'    },
    { name: "*Vinyl, White, Rail, 8'",              cost: 9.26,   category: 'vinyl'    },
    { name: "*Vinyl, White, U-Trim",                cost: 1.62,   category: 'vinyl'    },
    { name: "*Vinyl, Gate, Handle",                 cost: 5.98,   category: 'vinyl'    },
    { name: "*Vinyl, Tan, Rail, 8'",                cost: 10.18,  category: 'vinyl'    },
    { name: "*Vinyl, Tan, Post, Corner, 78\"",      cost: 12.90,  category: 'vinyl'    },
    { name: "*Vinyl, Tan, Post, End, 78\"",         cost: 12.90,  category: 'vinyl'    },
    { name: "*Vinyl, Tan, Post, Line, 78\"",        cost: 12.90,  category: 'vinyl'    },
    { name: "*Vinyl, Tan, Post, Corner, 102\"",     cost: 19.24,  category: 'vinyl'    },
    { name: "*Vinyl, Tan, Post, End, 102\"",        cost: 19.24,  category: 'vinyl'    },
    { name: "*Vinyl, Tan, Post, Line, 102\"",       cost: 19.24,  category: 'vinyl'    },
    { name: "*Vinyl, Tan, Picket",                  cost: 3.22,   category: 'vinyl'    },
    { name: "*Vinyl, Tan, Rail, 6'",                cost: 7.98,   category: 'vinyl'    },
    { name: "*Vinyl, Tan, U-Trim",                  cost: 1.85,   category: 'vinyl'    },
    { name: "Vinyl, Rail Insert, 8'",               cost: 8.00,   category: 'vinyl'    },
    { name: "Alum, Cap, 2\"",                       cost: 1.25,   category: 'hardware' },
    { name: "Alum, Gate, Hinge, Self-Closing",      cost: 33.36,  category: 'hardware' },
    { name: "Alum, Gate, Latch, AQUA, Black, 20\"", cost: 50.43,  category: 'hardware' },
    { name: "Alum, Gate, Latch",                    cost: 21.25,  category: 'hardware' },
    { name: "Black, Band, Brace",                   cost: 0.75,   category: 'hardware' },
    { name: "Black, Band, Tension",                 cost: 0.75,   category: 'hardware' },
    { name: "Black, Cap, Loop",                     cost: 1.14,   category: 'hardware' },
    { name: "Black, Cap, Post",                     cost: 1.01,   category: 'hardware' },
    { name: "Black, Collar",                        cost: 1.63,   category: 'hardware' },
    { name: "Black, Fork, 1-3/8\"",                cost: 1.53,   category: 'hardware' },
    { name: "Black, Fork, 2-1/2\"",                cost: 1.98,   category: 'hardware' },
    { name: "Black, Hinge, Female",                 cost: 1.24,   category: 'hardware' },
    { name: "Black, Hinge, Male",                   cost: 2.01,   category: 'hardware' },
    { name: "Black, Rail End",                      cost: 0.75,   category: 'hardware' },
    { name: "Black, Bolt, 3/8\" x 2\"",            cost: 0.41,   category: 'hardware' },
    { name: "Black, Bolt, 3/8\" x 3\"",            cost: 0.53,   category: 'hardware' },
    { name: "Black, Bolt, 5/16 x 1-1/4\"",         cost: 0.18,   category: 'hardware' },
    { name: "Drop Rod, 24\", Black",                cost: 30.48,  category: 'hardware' },
    { name: "Drop Rod, 48\", Black",                cost: 48.01,  category: 'hardware' },
    { name: "G, Band, Brace",                       cost: 0.69,   category: 'hardware' },
    { name: "G, Band, Tension",                     cost: 0.64,   category: 'hardware' },
    { name: "G, Cap, Loop",                         cost: 0.79,   category: 'hardware' },
    { name: "G, Cap, Post",                         cost: 0.96,   category: 'hardware' },
    { name: "G, Collar",                            cost: 1.29,   category: 'hardware' },
    { name: "G, Fork, 1-3/8\"",                    cost: 1.18,   category: 'hardware' },
    { name: "G, Fork, 2-1/2\"",                    cost: 1.53,   category: 'hardware' },
    { name: "G, Hinge, Female",                     cost: 0.83,   category: 'hardware' },
    { name: "G, Hinge, Male",                       cost: 0.83,   category: 'hardware' },
    { name: "G, Rail End",                          cost: 0.60,   category: 'hardware' },
    { name: "G, Bolt, 3/8\" x 2\"",               cost: 0.34,   category: 'hardware' },
    { name: "G, Bolt, 3/8\" x 3\"",               cost: 0.41,   category: 'hardware' },
    { name: "G, Bolt, 5/16 x 1-1/4\"",            cost: 0.15,   category: 'hardware' },
    { name: "G, Drop Rod, 24\"",                   cost: 6.88,   category: 'hardware' },
    { name: "*Vinyl, Gate, Brace",                  cost: 36.37,  category: 'vinyl'    },
    { name: "*Vinyl, Gate, Hinge",                  cost: 29.03,  category: 'vinyl'    },
    { name: "*Vinyl, Gate, Latch",                  cost: 20.46,  category: 'vinyl'    },
    { name: "*Vinyl, Tan, Upright",                 cost: 9.69,   category: 'vinyl'    },
    { name: "*Vinyl, White, Upright",               cost: 8.75,   category: 'vinyl'    },
    { name: "*Vinyl, Gate, P-Channel, 6'",          cost: 12.30,  category: 'vinyl'    },
    { name: "*Vinyl, Gate, H-Beam, 6'",             cost: 22.80,  category: 'vinyl'    },
    { name: "*Vinyl, Gate, H-Beam, 8'",             cost: 29.60,  category: 'vinyl'    },
    { name: "Vinyl, Tan, Cap, Gate",                cost: 1.00,   category: 'vinyl'    },
    { name: "*Vinyl, White, Cap, Gate",             cost: 1.00,   category: 'vinyl'    },
    { name: "Vinyl, Tan, Cap, 5x5",                 cost: 1.00,   category: 'vinyl'    },
    { name: "*Vinyl, White, Cap, 5x5",              cost: 1.00,   category: 'vinyl'    },
    { name: "Black, Hook Ties (100)",               cost: 14.00,  category: 'hardware' },
    { name: "Galv, Hook Ties (100)",                cost: 11.00,  category: 'hardware' },
    { name: "Black, Hog Ring",                      cost: 0.02,   category: 'hardware' },
    { name: "G, Hog Ring",                          cost: 0.02,   category: 'hardware' },
    { name: "Black, Wire, Tension",                 cost: 0.11,   category: 'hardware' },
    { name: "G, Wire, Tension",                     cost: 0.062,  category: 'hardware' },
    { name: "Comm, G, Fabric, 72\"",               cost: 258.75, category: 'commercial'},
    { name: "Comm, G, Term, 2-1/2\" X 6'",        cost: 59.00,  category: 'commercial'},
    { name: "Pipe, Galv, 2-1/2\" X 10'",          cost: 33.75,  category: 'commercial'},
    { name: "Pipe, Galv, 2\" X 12'",              cost: 36.13,  category: 'commercial'},
    { name: "Pipe, Galv, 1-5/8\" X 21'",          cost: 39.92,  category: 'commercial'},
    { name: "Pipe, Galv, 2\" X 10'",              cost: 32.50,  category: 'commercial'},
    { name: "Comm, G, Cap, Post",                   cost: 2.76,   category: 'commercial'},
    { name: "Comm, G, Cap, Loop",                   cost: 2.01,   category: 'commercial'},
    { name: "Comm, G, Rail End",                    cost: 1.85,   category: 'commercial'},
    { name: "Comm, G, Tension Bar, 72\"",          cost: 4.75,   category: 'commercial'},
    { name: "Comm, G, Barb Arm",                    cost: 4.75,   category: 'commercial'},
    { name: "Comm, G, Drop Rod",                    cost: 21.25,  category: 'commercial'},
    { name: "Comm, G, Barbed Wire",                 cost: 0.09,   category: 'commercial'},
    { name: "Comm, G, Sleeve",                      cost: 2.01,   category: 'commercial'},
    { name: "ND, Pipe, 2-1/2\" x 10'6\"",         cost: 29.80,  category: 'pipe'     },
    { name: "V, W, Post, 8' Privacy, CP",           cost: 24.56,  category: 'vinyl'    },
    { name: "V, W, Post, 8' Privacy, EP",           cost: 24.56,  category: 'vinyl'    },
    { name: "V, W, Post, 8' Privacy, LP",           cost: 24.56,  category: 'vinyl'    },
    { name: "V, W, Picket Section 8' x 6'",        cost: 108.68, category: 'vinyl'    },
    { name: "V, W, Picket Section 8' x 8'",        cost: 143.25, category: 'vinyl'    },
    { name: "V, W, Privacy Gate 8 x 4",             cost: 399.00, category: 'gate'     },
    { name: "V, W, Privacy Gate 8 x 5",             cost: 423.00, category: 'gate'     },
    { name: "V, W, Privacy Gate 8 x 6",             cost: 454.00, category: 'gate'     },
    { name: "V, T, Post, 8' Privacy, CP",           cost: 27.50,  category: 'vinyl'    },
    { name: "V, T, Post, 8' Privacy, EP",           cost: 27.50,  category: 'vinyl'    },
    { name: "V, T, Post, 8' Privacy, LP",           cost: 27.50,  category: 'vinyl'    },
    { name: "V, T, Picket Section 8' x 6'",        cost: 124.98, category: 'vinyl'    },
    { name: "V, T, Picket Section 8' x 8'",        cost: 164.74, category: 'vinyl'    },
    { name: "V, T, Privacy Gate 8 x 4",             cost: 458.00, category: 'gate'     },
    { name: "V, T, Privacy Gate 8 x 5",             cost: 486.00, category: 'gate'     },
    { name: "V, T, Privacy Gate 8 x 6",             cost: 522.00, category: 'gate'     },
    { name: "Alum, Ind, Sec, 6' x 8'",             cost: 211.62, category: 'section'  },
    { name: "Alum, Post 3\" x 8', CP",             cost: 71.93,  category: 'post'     },
    { name: "Alum, Post 3\" x 8', EP",             cost: 71.93,  category: 'post'     },
    { name: "Alum, Post 3\" x 8', LP",             cost: 71.93,  category: 'post'     },
    { name: "Alum, Cap, 3\"",                      cost: 2.50,   category: 'hardware' },
    { name: "Alum, Hex, 1/4\"",                    cost: 0.17,   category: 'hardware' },
    { name: "Ag, Tube Gate, 4' x 4'",              cost: 99.99,  category: 'gate'     },
    { name: "Ag, Tube Gate, 4' x 6'",              cost: 109.99, category: 'gate'     },
    { name: "Ag, Tube Gate, 4' x 8'",              cost: 99.99,  category: 'gate'     },
    { name: "Ag, Tube Gate, 4' x 10'",             cost: 119.99, category: 'gate'     },
    { name: "Ag, Tube Gate, 4' x 12'",             cost: 129.99, category: 'gate'     },
    { name: "Ag, Tube Gate, 4' x 14'",             cost: 149.99, category: 'gate'     },
    { name: "Ag, Tube Gate, 4' x 16'",             cost: 169.99, category: 'gate'     },
    { name: "Ag, Tube Gate, 4' x 18'",             cost: 199.99, category: 'gate'     },
    { name: "Ag, Tube Gate, 4' x 20'",             cost: 219.99, category: 'gate'     },
    { name: "Ag, Gate, Hardware, 2 Way Latch",      cost: 23.39,  category: 'hardware' },
    { name: "Ag, Wire Mesh Gate, 4' x 4'",         cost: 166.69, category: 'gate'     },
    { name: "Ag, Wire Mesh Gate, 4' x 6'",         cost: 176.66, category: 'gate'     },
    { name: "Ag, Wire Mesh Gate, 4' x 8'",         cost: 193.62, category: 'gate'     },
    { name: "Ag, Wire Mesh Gate, 4' x 10'",        cost: 169.99, category: 'gate'     },
    { name: "Ag, Wire Mesh Gate, 4' x 12'",        cost: 233.11, category: 'gate'     },
    { name: "Ag, Wire Mesh Gate, 4' x 14'",        cost: 219.99, category: 'gate'     },
    { name: "Ag, Wire Mesh Gate, 4' x 16'",        cost: 239.99, category: 'gate'     },
    { name: "Comm, Blk, Term, 2-1/2\" X 10'",     cost: 43.90,  category: 'commercial'},
    { name: "Comm, Blk, Line, 2\" X 10'",         cost: 26.50,  category: 'commercial'},
    { name: "Gate, Emily 2R, 4 x 4",               cost: 168.83, category: 'gate'     },
    { name: "Gate, Emily 2R, 4 x 5",               cost: 183.69, category: 'gate'     },
    { name: "Emily 2R, Panel, 48\" x 6'",          cost: 56.06,  category: 'section'  },
    { name: "Emily 2R, CP x 6'",                   cost: 17.04,  category: 'post'     },
    { name: "Emily 2R, EP x 6'",                   cost: 17.04,  category: 'post'     },
    { name: "Emily 2R, LP x 6'",                   cost: 17.04,  category: 'post'     },
    { name: "Alum, Emily 3R-Pup, Gate, 4 x 4",     cost: 232.99, category: 'gate'     },
    { name: "Alum, Emily 3R-Pup, Gate, 4 x 5",     cost: 255.41, category: 'gate'     },
    { name: "Alum, Emily 3R-Pup, Sec, 48\" x 6'", cost: 129.79, category: 'section'  },
    { name: "Alum, Emily 3R-Pup, Post, CP",        cost: 19.80,  category: 'post'     },
    { name: "Alum, Emily 3R-Pup, Post, EP",        cost: 19.80,  category: 'post'     },
    { name: "Alum, Emily 3R-Pup, Post, LP",        cost: 19.80,  category: 'post'     },
    { name: "Gr, Fabric, 48\"",                    cost: 122.85, category: 'fabric'   },
    { name: "Pipe, Grn, 1-3/8\" X 21'",           cost: 28.40,  category: 'pipe'     },
    { name: "Gr, Tension Bar, 48\"",               cost: 3.45,   category: 'hardware' },
    { name: "Pipe, Grn, 2-1/2\" X 8'",            cost: 21.65,  category: 'pipe'     },
    { name: "Pipe, Grn, 1-5/8\" X 8'",            cost: 13.63,  category: 'pipe'     },
  ];

  for (const item of inventoryItems) {
    await prisma.inventoryItem.upsert({
      where:  { name: item.name },
      update: { cost: item.cost, category: item.category },
      create: { name: item.name, cost: item.cost, category: item.category },
    });
  }
  console.log(`  ✓ ${inventoryItems.length} inventory items`);
  console.log('\nSeed complete.');
}

main()
  .catch(e => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());